
package client.wsdlGenerated;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     * @return
     *     returns java.util.List<client.wsdlGenerated.WsTournament>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllClosedMatches", targetNamespace = "http://Server/", className = "client.wsdlGenerated.GetAllClosedMatches")
    @ResponseWrapper(localName = "getAllClosedMatchesResponse", targetNamespace = "http://Server/", className = "client.wsdlGenerated.GetAllClosedMatchesResponse")
    @Action(input = "http://Server/WebServiceInterface/getAllClosedMatchesRequest", output = "http://Server/WebServiceInterface/getAllClosedMatchesResponse")
    public List<WsTournament> getAllClosedMatches();

}
